# Generated by Django 5.0.3 on 2024-04-01 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=254)),
                ('notes', models.CharField(blank=True, max_length=65, null=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, max_length=65)),
                ('description', models.CharField(max_length=254)),
                ('brand', models.CharField(blank=True, max_length=65)),
                ('model', models.CharField(blank=True, max_length=65)),
                ('condition', models.CharField(blank=True, max_length=65)),
                ('notes', models.CharField(blank=True, max_length=65, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
            ],
        ),
    ]
