# Generated by Django 5.0.3 on 2024-04-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
