# Generated by Django 5.0.3 on 2024-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='location_name',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
